// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqLYpeGfAxbNNdbUrNDBMZwnN8cUPcAmI',
    appId: '1:703805974821:web:e90aa224a196b9b3dd12cc',
    messagingSenderId: '703805974821',
    projectId: 'ekart-3372f',
    authDomain: 'ekart-3372f.firebaseapp.com',
    storageBucket: 'ekart-3372f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKvIbIVZHHe527eJu_XtsiXKdMgaLOo4',
    appId: '1:703805974821:android:9d4d95801d82b1e1dd12cc',
    messagingSenderId: '703805974821',
    projectId: 'ekart-3372f',
    storageBucket: 'ekart-3372f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxuixZ9IsC7papu3BKEqY4YXRllxdBbAM',
    appId: '1:703805974821:ios:0ec972bde02bfa0fdd12cc',
    messagingSenderId: '703805974821',
    projectId: 'ekart-3372f',
    storageBucket: 'ekart-3372f.appspot.com',
    iosBundleId: 'com.example.ecart',
  );
}
